'use client'

export function generateAgreementHTML(data: {
  tenantName: string
  nationalId: string
  phone: string
  email: string
  landlordName: string
  propertyName: string
  location: string
  unitNumber: string
  rentAmount: number
  depositAmount: number
  startDate: string
  signedAt: string
}) {
  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #1A1A1A; margin: 40px; line-height: 1.6; }
  h1 { font-size: 15px; text-align: center; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
  h2 { font-size: 12px; margin: 16px 0 6px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .center { text-align: center; }
  .meta { color: #666; font-size: 10px; text-align: center; margin-bottom: 20px; }
  .parties { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 16px 0; }
  .party { background: #f9f9f9; padding: 12px; border-radius: 4px; border: 1px solid #e0e0e0; }
  .party-label { font-weight: bold; font-size: 10px; text-transform: uppercase; color: #666; margin-bottom: 6px; }
  .clause { margin-bottom: 10px; }
  .clause-num { font-weight: bold; }
  .signature-block { margin-top: 24px; border-top: 1px solid #ccc; padding-top: 16px; }
  .sig-row { display: flex; justify-content: space-between; margin-top: 12px; }
  .sig-box { width: 45%; }
  .sig-line { border-bottom: 1px solid #333; margin-bottom: 4px; height: 20px; }
  .sig-label { font-size: 10px; color: #666; }
  .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
  .highlight { background: #1B3A2D; color: white; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
</style>
</head>
<body>
<h1>The Ardhi Platform</h1>
<h1>Tenancy Agreement</h1>
<p class="meta">Generated on ${data.signedAt} · Ref: ARD-${Date.now().toString().slice(-8)}</p>

<div class="parties">
  <div class="party">
    <div class="party-label">Landlord</div>
    <strong>${data.landlordName}</strong>
  </div>
  <div class="party">
    <div class="party-label">Tenant</div>
    <strong>${data.tenantName}</strong><br/>
    NID: ${data.nationalId}<br/>
    Phone: ${data.phone}<br/>
    Email: ${data.email}
  </div>
</div>

<h2>1. Premises</h2>
<p class="clause">The Landlord lets to the Tenant the premises known as Unit <strong>${data.unitNumber}</strong>, <strong>${data.propertyName}</strong>, located at <strong>${data.location}</strong>, Uganda ("the Premises").</p>

<h2>2. Term</h2>
<p class="clause">This tenancy commences on <strong>${data.startDate}</strong> and continues on a month-to-month basis unless terminated by either party giving thirty (30) days' written notice through the platform.</p>

<h2>3. Rent & Deposit</h2>
<p class="clause">Monthly rent: <strong>UGX ${data.rentAmount.toLocaleString()}</strong>, due on the 1st of each month via the The Ardhi platform. Security deposit: <strong>UGX ${data.depositAmount.toLocaleString()}</strong>, refundable within 30 days of vacating less lawful deductions.</p>

<h2>4. Tenant Obligations</h2>
<p class="clause">The Tenant shall: (a) use the Premises solely for lawful purposes; (b) maintain the Premises in good clean condition; (c) not sublet without written consent from the Landlord; (d) not cause nuisance to other occupants; (e) report maintenance issues promptly via the platform.</p>

<h2>5. Landlord Obligations</h2>
<p class="clause">The Landlord shall: (a) maintain the Premises in habitable condition; (b) ensure essential services where applicable; (c) give 24 hours' notice before entering the Premises except in emergency.</p>

<h2>6. Termination</h2>
<p class="clause">Either party may terminate with 30 days' written notice. The Landlord may terminate immediately upon material breach of any term herein.</p>

<h2>7. Governing Law</h2>
<p class="clause">This Agreement is governed by the laws of Uganda including the Landlord and Tenant Act, Cap 231 and the Mortgage Act.</p>

<h2>8. Digital Execution</h2>
<p class="clause">The Tenant's acceptance on The Ardhi platform, together with timestamp and IP address recorded below, constitutes a valid and binding digital signature under the Electronic Transactions Act, 2011 (Uganda).</p>

<div class="signature-block">
  <strong>Execution</strong>
  <div class="sig-row">
    <div class="sig-box">
      <div class="sig-line"></div>
      <div class="sig-label">Tenant: ${data.tenantName}</div>
      <div class="sig-label">Signed digitally on ${data.signedAt}</div>
    </div>
    <div class="sig-box">
      <div class="sig-line"></div>
      <div class="sig-label">Landlord: ${data.landlordName}</div>
      <div class="sig-label">Property: ${data.propertyName}</div>
    </div>
  </div>
</div>

<div class="footer">
  Generated by The Ardhi Property Management Platform · theardhi.app<br/>
  This document is legally binding under the laws of Uganda.
</div>
</body>
</html>
`
}

export async function downloadAgreementPDF(data: Parameters<typeof generateAgreementHTML>[0]) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const html = generateAgreementHTML(data)
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)

  return new Promise<void>((resolve) => {
    doc.html(html, {
      callback: (pdf) => {
        pdf.save(`Ardhi-Tenancy-Agreement-${data.tenantName.replace(/\s/g, '-')}.pdf`)
        URL.revokeObjectURL(url)
        resolve()
      },
      x: 10, y: 10, width: 190, windowWidth: 800,
    })
  })
}
